# Generated by Django 4.0.4 on 2022-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_category_product_color_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('T', 'Tablet'), ('L', 'Laptop'), ('D', 'Desktop'), ('F', 'Fashion'), ('G', 'Gadgets'), ('H', 'None')], default='N', max_length=100),
        ),
    ]
